ManejoPresupuesto/Controllers/TiposCuentasController.cs
using Dapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace ManejoPresupuesto.Controllers
{
    public class TiposCuentasController : Controller
    {

        /* Declaración de dependencias necesarias para el controlador, incluyendo el repositorio de tipos de cuentas y el servicio de usuarios */
        #region Dependencias del controlador
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuarios servicioUsuarios;

        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuenta, IServicioUsuarios servicioUsuarios)
        {
            this.repositorioTiposCuentas = repositorioTiposCuenta;
            this.servicioUsuarios = servicioUsuarios;
        }
        #endregion

        /* Método de acción para mostrar el índice de tipos de cuentas, obteniendo y pasando los tipos de cuentas del usuario a la vista */
        #region Vista para Índice de Tipos de Cuentas

        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            // Obtiene todos los 'TipoCuenta' para el usuario con ID 1 de la base de datos.
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            // Devuelve la vista 'Index', pasando la lista de 'TipoCuenta' como modelo.
            return View(tiposCuentas);
        }
        #endregion

        #region Crear Tipo de Cuenta
        // Acción para mostrar el formulario de creación de un nuevo tipo de cuenta
        #region Vista para Crear Tipo de Cuenta
        public IActionResult Crear()
        {
            return View();
        }
        #endregion

        // Acción para procesar el formulario de creación de un tipo de cuenta, validando datos y guardando en la base de datos
        #region Procesar Creación de Tipo de Cuenta

        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuenta tipoCuenta) // Método de acción para crear un nuevo 'TipoCuenta'.
        {
            // Verifica si el modelo es válido.
            if (!ModelState.IsValid)
            {
                // Si el modelo no es válido, vuelve a la vista con el modelo actual (que contiene los errores de validación).
                return View(tipoCuenta);
            }

            tipoCuenta.UsuarioId = servicioUsuarios.ObtenerUsuarioId();
  

            // Verifica si ya existe un 'TipoCuenta' con el mismo nombre para el mismo usuario.
            var yaExisteTipoCuenta =
                await repositorioTiposCuentas.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);

            // Si ya existe un 'TipoCuenta' con el mismo nombre...
            if (yaExisteTipoCuenta)
            {
                // Agrega un error al modelo indicando que el nombre ya existe.
                ModelState.AddModelError(nameof(tipoCuenta.Nombre), $"El nombre {tipoCuenta.Nombre} ya existe.");
                // Vuelve a la vista con el modelo actual (que contiene el error).
                return View(tipoCuenta);
            }

            // Si no hay errores, crea el nuevo 'TipoCuenta' en la base de datos.
            await repositorioTiposCuentas.Crear(tipoCuenta);
            // Redirige al usuario a la acción 'Index' del controlador.
            return RedirectToAction("Index");
        }
        #endregion
        #endregion

        #region Editar Tipo de Cuenta
        // Acción para mostrar el formulario de edición de un tipo de cuenta específico
        #region Vista para Editar Tipo de Cuenta
        [HttpGet]
        public async Task<ActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerXid(id, usuarioId);

            if (tipoCuenta == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }
        #endregion

        // Acción para procesar el formulario de edición de un tipo de cuenta, validando datos y actualizando en la base de datos
        #region Procesar Edición de Tipo de Cuenta

        [HttpPost]
        public async Task<ActionResult> Editar(TipoCuenta tipoCuenta)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuentaExiste = await repositorioTiposCuentas.ObtenerXid(tipoCuenta.id, usuarioId);
            if (tipoCuentaExiste == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTiposCuentas.Actualizar(tipoCuenta);
            return RedirectToAction("Index");
        }
        #endregion
        #endregion


        // Acción para verificar si ya existe un tipo de cuenta con el nombre proporcionado para el usuario
        #region Verificar Existencia de Tipo de Cuenta por Nombre
        [HttpGet]
        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre)
        {
            var usuarioId = 1;
            // Verifica si ya existe un 'TipoCuenta' con el nombre proporcionado para el usuario con ID 1.
            var yaExisteTipoCuenta = await repositorioTiposCuentas.Existe(nombre, usuarioId);
            // Si ya existe un 'TipoCuenta' con el nombre proporcionado...
            if (yaExisteTipoCuenta)
            {

                // Devuelve una respuesta JSON indicando que el nombre ya existe.
                return Json($"El nombre {nombre} ya existe.");
            }
            // Si no existe un 'TipoCuenta' con el nombre proporcionado, devuelve una respuesta JSON con 'true'.
            return Json(true);
        }
        #endregion


        // Acción para mostrar la vista de confirmación de eliminación de un tipo de cuenta específico
        #region Acción de Vista para Confirmación de Eliminación de Tipo de Cuenta
        public async Task<ActionResult> Eliminar(int id)
        {
            // Obtiene el ID del usuario actualmente autenticado.
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            // Intenta obtener el 'TipoCuenta' con el ID proporcionado que pertenece al usuario actual.
            var tipoCuenta = await repositorioTiposCuentas.ObtenerXid(id, usuarioId);
            // Si no se encuentra ningún 'TipoCuenta' con el ID proporcionado para el usuario actual...
            if (tipoCuenta == null)
            {
                // Redirige al usuario a la vista 'NoEncontrado' del controlador 'Home'.
                return RedirectToAction("NoEncontrado", "Home");
            }
            // Si se encuentra un 'TipoCuenta', devuelve la vista de eliminación, pasando el 'TipoCuenta' como modelo.
            return View(tipoCuenta);
        }
        #endregion

        // Acción para procesar la eliminación de un tipo de cuenta, verificando que pertenezca al usuario.
        #region Procesar Eliminación de Tipo de Cuenta

        [HttpPost]
        public async Task<ActionResult> EliminarTipoCuenta(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerXid(id, usuarioId);

            if (tipoCuenta == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            // Si se encuentra un 'TipoCuenta', lo elimina de la base de datos.
            await repositorioTiposCuentas.Eliminar(id);
            // Redirige al usuario a la vista 'Index' del controlador.
            return RedirectToAction("Index");
        }
        #endregion


        // Acción para actualizar el orden de los tipos de cuentas de un usuario
        #region Procesar Ordenamiento de Tipos de Cuentas

        [HttpPost]
        public async Task<IActionResult> Ordenar([FromBody] int[] ids)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            var idsTipoCuenta = tiposCuentas.Select(x => x.id);

            var idsTiposCuentasNoPerteneceAlUsuario = ids.Except(idsTipoCuenta).ToList();

            if (idsTiposCuentasNoPerteneceAlUsuario.Count() > 0)
            {
                return Forbid();
            }
            var tipoCuentasOrdenados = ids.Select((valor, indice) => new TipoCuenta()
            {
                id = valor,
                Orden = indice + 1
            }).AsEnumerable();

            await repositorioTiposCuentas.Ordenar(tipoCuentasOrdenados);
            return Ok();
        }
        #endregion



    }
}

ManejoPresupuesto/Views/TiposCuentas/Crear.cshtml
@model TipoCuenta
@*
    Se espera que la vista reciba un solo objeto de tipo TipoCuenta
*@

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear Tipo de Cuenta</h1>

<h5>
    El tipo de cuenta se refiere a como podemos agrupar cuentas.
    Ejemplos: Prestamos, tarjetas de credito, etc.
</h5>
<!-- 
 ModelOnly significa que solo se incluirán los errores asociados directamente con las propiedades del modelo, 
y no los errores asociados con el ModelState en general.-->
<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-action="Crear" asp-controller="TiposCuentas">
    <div class="mb-3">
        <!-- Etiqueta para el campo de entrada 'Nombre'.
        El atributo 'asp-for' vincula esta etiqueta con la propiedad 'Nombre' del modelo. -->
        <label asp-for="Nombre" class="form-label"></label>
        <input class="form-control" asp-for="Nombre" type="text" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>


 @section Scripts {
    <!-- Esta vista parcial contiene scripts de validación de formularios. -->
<partial name="_ValidationScriptsPartial"/>
 }

ManejoPresupuesto/Views/TiposCuentas/Editar.cshtml
@*
    Se espera que la vista reciba un solo objeto de tipo TipoCuenta
*@
@model TipoCuenta

@{
    ViewData["Title"] = "Editar Tipo Cuenta";

}

<h1>Editar Tipo Cuenta: @Model.Nombre</h1>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<!-- Un contenedor que muestra un resumen de todos los errores de validación del modelo.
Los errores se mostrarán en color rojo debido a la clase 'text-danger'. -->

<!-- Inicio del formulario. Cuando se envía, se invoca la acción 'Editar' del controlador. -->
<form asp-action="Editar">
    <!-- Un campo de entrada oculto que almacena el ID del 'TipoCuenta'.
    El atributo 'asp-for' vincula este campo de entrada con la propiedad 'id' del modelo. -->
    <input type="hidden" asp-for="id" />
    <div class="mb-3">
        <!-- Etiqueta para el campo de entrada 'Nombre'.
        El atributo 'asp-for' vincula esta etiqueta con la propiedad 'Nombre' del modelo. -->
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <!-- Un contenedor que muestra los errores de validación para el campo 'Nombre'.
        Los errores se mostrarán en color rojo debido a la clase 'text-danger'. -->
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ManejoPresupuesto/Views/TiposCuentas/Eliminar.cshtml
@model TipoCuenta


@{
    ViewData["Title"] = "Borrar tipo cuenta";
}

<h3 class="mb-3">¿Está seguro que desea borrar el tipo cuenta @Model.Nombre</h3>

<form asp-action="EliminarTipoCuenta">
    <input type="hidden" asp-for="id" />
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

ManejoPresupuesto/Views/TiposCuentas/Index.cshtml
@model IEnumerable<TipoCuenta>
@*
    Se espera que la vista reciba una colección de objetos TipoCuenta
*@
@{
    ViewData["Title"] = "Tipos Cuentas";
}

<h1>Tipos de Cuentas</h1>
<h5>
    El tipo de cuenta se refiere a cómo podemos agrupar cuentas.
    Ejemplos: Préstamos, tarjetas de crédito, etc.
</h5>

<a asp-action="Crear" class="btn btn-primary mb-3">Crear nuevo</a>

<table class="table">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <!-- El bucle 'foreach' se utiliza para generar una fila en la tabla HTML para cada 'TipoCuenta' en la colección 'Model'. -->
    <tbody id="reordenable">
        @foreach (var tipoCuenta in Model)
        {
            <tr>
                <td>
                    <!-- Un campo de entrada oculto que almacena el ID del 'TipoCuenta' actual. -->
                    <input type="hidden" value="@tipoCuenta.id" class="ids" />
                    <!-- Un enlace que actúa como botón para editar el 'TipoCuenta' actual.
                    El atributo 'asp-action' indica que la acción del controlador a invocar es 'Editar'.
                    El atributo 'asp-route-id' pasa el ID del 'TipoCuenta' actual a la acción del controlador. -->
                    <a class="btn btn-primary" asp-action="Editar" asp-route-id="@tipoCuenta.id">Editar</a>
                    <a class="btn btn-danger" asp-action="Eliminar" asp-route-id="@tipoCuenta.id">Borrar</a>
                </td>
                <td>
                    <!-- Muestra el nombre del 'TipoCuenta' actual. -->
                    @tipoCuenta.Nombre

                </td>
            </tr>
        }
    </tbody>

</table>


@section Scripts {
    <script>
        const urlOrdenar = '@Url.Action("ordenar")';

        $(function () {
            $("#reordenable").sortable({
                stop: async function (e, ui) {
                    await actualizarOrdenes();
                }
            });
            async function actualizarOrdenes() {
                const ids = obtenerIdElementos();
                await enviarIdAlBackend(ids);

            }

            function obtenerIdElementos() {
                const ids = $(".ids").map(function () {
                    return $(this).val();
                }).get();

                return ids;
            }

            async function enviarIdAlBackend(ids) {
                ;
                var data = JSON.stringify(ids);

                await fetch(urlOrdenar, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'Content-Type': 'application/json'
                    },
                });
            }

        });


    </script>

}