ManejoPresupuesto/Models/ReporteTransaccionesDetalladas.cs
namespace ManejoPresupuesto.Models
{
    public class ReporteTransaccionesDetalladas
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set;}
        // Esto almacena las transacciones agrupadas por fecha.
        public IEnumerable<TransaccionesPorFecha> TransaccionesAgrupadas { get; set; }
        // Calculamos el balance de depósitos sumando los BalanceDepositos de todas las transacciones agrupadas.
        public decimal BalanceDepositos => TransaccionesAgrupadas.Sum(x => x.BalanceDepositos);
        // Calculamos el balance de retiros sumando los BalanceRetiros de todas las transacciones agrupadas.
        public decimal BalanceRetiros => TransaccionesAgrupadas.Sum(x => x.BalanceRetiros);
        // Calculamos el balance total restando el balance de retiros del balance de depósitos.
        public decimal Total => BalanceDepositos - BalanceRetiros;

        // Definimos una clase interna TransaccionesPorFecha que agrupa transacciones por fecha.
        public class TransaccionesPorFecha {
            // almacena la fecha de la transacción.
            public DateTime FechaTransaccion {  get; set; }
            // Propiedad Transacciones que es un conjunto de Transaccion. Esto almacena las transacciones.
            public IEnumerable<Transaccion> Transacciones { get; set;}
            // Calculamos el balance de depósitos para esta fecha filtrando y sumando las transacciones de tipo ingreso.
            public decimal BalanceDepositos => Transacciones.Where(x => x.tipoOperacionId == TipoOperacion.Ingreso).Sum(x => x.Monto);
            // Calculamos el balance de retiros para esta fecha filtrando y sumando las transacciones de tipo gasto.
            public decimal BalanceRetiros => Transacciones.Where(x => x.tipoOperacionId == TipoOperacion.Gasto).Sum(x => x.Monto);


        }
    }
}

ManejoPresupuesto/Models/ResumenMontosViewModel.cs
namespace ManejoPresupuesto.Models
{
    public class ResumenMontosViewModel
    {
        public decimal Ingresos { get; set; }
        public decimal Gastos { get; set; }
        public decimal Total { get; set; }
    }
}

ManejoPresupuesto/Controllers/CuentasController.cs
using AutoMapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ManejoPresupuesto.Controllers
{
    public class CuentasController : Controller
    {

        /* Declaración de dependencias utilizadas por el controlador para gestionar tipos de cuentas, usuarios, transacciones y reportes */
        #region Dependencias del controlador
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuarios servicioUsuarios;
        private readonly IRepositorioCuentas repositorioCuentas;
        private readonly IMapper mapper;
        private readonly IRepositorioTransacciones repositorioTransacciones;
        private readonly IServicioReportes servicioReportes;
        /* Constructor del CuentasController para la inyección de dependencias necesarias para las operaciones de cuentas */
        public CuentasController(IRepositorioTiposCuentas _repositorioTiposCuentas, IServicioUsuarios _servicioUsuarios,
            IRepositorioCuentas _repositorioCuentas, IMapper _mapper, IRepositorioTransacciones _repositorioTransacciones,
            IServicioReportes _servicioReportes)
        {
            this.repositorioTiposCuentas = _repositorioTiposCuentas;
            this.servicioUsuarios = _servicioUsuarios;
            this.repositorioCuentas = _repositorioCuentas;
            this.mapper = _mapper;
            this.repositorioTransacciones = _repositorioTransacciones;
            this.servicioReportes = _servicioReportes;
        }
        #endregion

        #region Crear Cuenta
        // Acción para mostrar el formulario de creación de una nueva cuenta, cargando los tipos de cuentas disponibles
        #region Acción de Vista para Crear Cuenta

        [HttpGet]
        public async Task<IActionResult> Crear() // Método asíncrono que maneja la creación de una nueva cuenta
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId(); // Obtiene el ID del usuario actual
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId); // Obtiene los tipos de cuentas para el usuario actual de forma asíncrona
            var modelo = new CuentaCreacionViewModel(); // Crea una nueva instancia del modelo de creación de cuenta
            // Convierte los tipos de cuentas en elementos seleccionables para una lista desplegable
            modelo.TiposCuentas = tiposCuentas.Select(x => new SelectListItem(x.Nombre, x.id.ToString()));
            return View(modelo);// Devuelve la vista con el modelo de datos
        }
        #endregion

        // Acción para procesar el formulario de creación de cuenta, validando datos y guardando en la base de datos
        #region Procesar Creación de Cuenta

        //Este código se utiliza para procesar y validar los datos del formulario de creación de cuentas,
        //manejar errores y finalmente agregar la nueva cuenta a la base de datos si todos los datos son correctos.
        [HttpPost]
        public async Task<IActionResult> Crear(CuentaCreacionViewModel cuenta)  // Método asíncrono que maneja la creación de una nueva cuenta
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.ObtenerXid(cuenta.TipoCuentaId, usuarioId); // Obtiene el tipo de cuenta especificado para el usuario actual

            if (tiposCuentas is null) // Si el tipo de cuenta no se encuentra
            {
                return RedirectToAction("NoEncontrado", "Home"); // Redirige a la acción "NoEncontrado" en el controlador "Home"

            }
            if (!ModelState.IsValid) // Si el modelo no es válido
            {
                cuenta.TiposCuentas = await ObtenerTiposCuentas(usuarioId); // Obtiene los tipos de cuentas del usuario y los asigna al modelo
                return View(cuenta);// Devuelve la vista con el modelo actual para corregir errores
            }

            await repositorioCuentas.Crear(cuenta); // Crea la nueva cuenta en el repositorio
            return RedirectToAction("Index"); // Redirige a la acción "Index" del controlador actual
        }
        #endregion

        #endregion


        // Acción para mostrar el índice de cuentas, agrupando las cuentas del usuario por tipo de cuenta
        #region Vista para Índice de Cuentas
        //Este código se utiliza para preparar y mostrar los datos en la página de índice de cuentas,
        //proporcionando una visión general de las cuentas del usuario agrupadas por tipo de cuenta.
        public async Task<IActionResult> Index()  // Método asíncrono que maneja la vista de la página de índice de cuentas
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuentasConTipoCuenta = await repositorioCuentas.Buscar(usuarioId); // Obtiene las cuentas del usuario con sus tipos de cuenta asociados

            var modelo = cuentasConTipoCuenta // Crea el modelo de vista para la página de índice de cuentas
                .GroupBy(x => x.TipoCuenta) // Agrupa las cuentas por tipo de cuenta
                .Select(grupo => new IndiceCuentasViewModel  // Crea un objeto IndiceCuentasViewModel para cada grupo de cuentas
                {
                    TipoCuenta = grupo.Key, // Establece el tipo de cuenta para el modelo
                    Cuentas = grupo.AsEnumerable() // Asigna las cuentas correspondientes al tipo de cuenta
                }).ToList();

            return View(modelo); // Devuelve la vista con el modelo de datos para mostrar en la página de índice de cuentas
        }
        #endregion

        #region Editar Cuentas
        // Acción para mostrar el formulario de edición de una cuenta específica, cargando datos de tipos de cuentas del usuario
        #region Vista para Editar Cuenta

        // Método asíncrono que edita una cuenta y devuelve una vista.
        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            // Mapea la cuenta a un modelo de vista de creación de cuenta.
            var modelo = mapper.Map<CuentaCreacionViewModel>(cuenta);
            // Obtiene los tipos de cuentas para el usuario actual.
            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
            // Devuelve la vista con el modelo de datos.
            return View(modelo);

        }
        #endregion

        // Acción para procesar el formulario de edición de cuenta, validando datos y guardando cambios en la base de datos
        #region Procesar Edición de Cuenta

        //El método GET prepara y muestra la página de edición. El método POST procesa y guarda los cambios realizados en la cuenta.
        [HttpPost]
        public async Task<IActionResult> Editar(CuentaCreacionViewModel cuentaEditar)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(cuentaEditar.id, usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            // Obtiene el tipo de cuenta por su id y el id del usuario.
            var tipoCuenta = await repositorioTiposCuentas.ObtenerXid(cuentaEditar.TipoCuentaId, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioCuentas.Actualizar(cuentaEditar);
            return RedirectToAction("Index");
        }
        #endregion

        #endregion

        #region BorrarCuentas
        // Acción para mostrar la confirmación de borrado de una cuenta específica
        #region Vista para Confirmación de Borrado de Cuenta

        // método asíncrono se utiliza para preparar y mostrar una vista que permite al usuario confirmar la eliminación de una cuenta. 
        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(cuenta);
        }
        #endregion

        // Acción para procesar el borrado de una cuenta, eliminándola de la base de datos
        #region Procesar Borrado de Cuenta

        [HttpPost]
        public async Task<IActionResult> BorrarCuenta(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioCuentas.Borrar(id);
            return RedirectToAction("Index");
        }
        #endregion
        #endregion


        // Método privado para obtener los tipos de cuentas del usuario y prepararlos como elementos de una lista desplegable
        #region Obtener Tipos de Cuentas para Lista de Selección
        //Este metodo es útil en situaciones donde se necesita obtener y preparar los tipos de cuentas para su presentación en la interfaz de usuario,
        //como en formularios de creación o edición de cuentas, donde se puede necesitar una lista desplegable para seleccionar el tipo de cuenta asociado.
        private async Task<IEnumerable<SelectListItem>> ObtenerTiposCuentas(int usuarioId) // Método privado asíncrono que obtiene los tipos de cuentas del usuario
        {
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId); 

ManejoPresupuesto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManejoPresupuesto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManejoPresupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="ManejoPresupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css" />




</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Transacciones" asp-action="Index">ManejoPresupuesto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Transacciones" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacciones" asp-action="Crear">Transacciones</a>
                        </li>
                    </ul>
                    <partial name="_LinksLogin"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ManejoPresupuesto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ManejoPresupuesto/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">
                Registro
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">
                Login
            </a>
        </li>
    }
</ul>


@{

}

ManejoPresupuesto/Views/Shared/_NavegarPorMeses.cshtml
@model DateTime

<h4>
    <!-- Sección de navegación entre meses -->
    <!-- Botón para navegar al mes anterior usando ViewBag para los parámetros mes y año -->
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-año="@ViewBag.añoAnterior" class="btn btn-secondary">
        <i class="bi-chevron-left"></i>
    </a>
    <!-- Botón para navegar al mes anterior usando ViewBag para los parámetros mes y año -->
    @Model.ToString("MMM")-@Model.Year
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-año="@ViewBag.añoPosterior" class="btn btn-secondary">
        <i class="bi-chevron-right"></i>
    </a>
</h4>

ManejoPresupuesto/Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model ReporteTransaccionesDetalladas

@{
    var resumenMontos = new ResumenMontosViewModel()
    {
      Ingresos = Model.BalanceDepositos,
      Gastos = Model.BalanceRetiros,
      Total = Model.Total
    };
}

<h1>Movimientos @ViewBag.Cuenta</h1>

<partial name="_NavegarPorMeses" model="@Model.FechaInicio" />
<partial name="_ResumenMontos" model="@resumenMontos" />
<!-- Condicional que verifica si no hay transacciones agrupadas -->
@if (Model.TransaccionesAgrupadas.Count() == 0)
{
    <h5>No hay datos para mostrar</h5>
}
else
{
    <!-- Si hay transacciones agrupadas, se genera una tabla -->
    <table class="table">
        <tbody>
            <!-- Itera sobre cada grupo de transacciones agrupadas por fecha -->
            @foreach (var transaccionAgrupada in Model.TransaccionesAgrupadas)
            {
                <!-- Fila con estilo personalizado para mostrar la fecha de las transacciones -->
                <tr style="background-color: lightcyan; font-size: 26px">
                    <td colspan="3">
                        <span class="badge bg-secondary">
                            <!-- Muestra el día de la transacción -->
                            @transaccionAgrupada.FechaTransaccion.Day
                        </span>
                        <span class="badge bg-secondary">
                            <!-- Muestra el día de la semana de la transacción -->
                            @transaccionAgrupada.FechaTransaccion.ToString("ddd")
                        </span>
                    </td>
                    <!-- Muestra el balance de depósitos y retiros del grupo de transacciones -->
                    <td class="activo">@transaccionAgrupada.BalanceDepositos.ToString("N")</td>
                    <td class="pasivo">@transaccionAgrupada.BalanceRetiros.ToString("N")</td>

                </tr>
                <!-- Se generan las filas para cada transacción individual dentro del grupo -->
                @foreach (var transaccion in transaccionAgrupada.Transacciones)
                {
                    <tr style="vertical-align: middle">
                        <td>
                            <!-- Enlace para editar la transacción actual, usando el ID de la transacción -->
                            <a asp-controller="Transacciones" asp-action="Editar" asp-route-id="@transaccion.id"
                               asp-route-UrlRetorno="@ViewBag.UrlRetorno">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>
                        <!-- Muestra la categoría de la transacción -->
                        <td>@transaccion.Categoria</td>
                        <!-- Muestra el nombre de la cuenta a la que pertenece la transacción -->
                        <td>@transaccion.Cuenta</td>
                        <!-- Muestra el monto si la transacción es un ingreso -->
                        <td class="activo">@(transaccion.tipoOperacionId == TipoOperacion.Ingreso ? transaccion.Monto.ToString("N"): null)</td>
                        <!-- Muestra el monto si la transacción es un gasto -->
                        <td class="pasivo">@(transaccion.tipoOperacionId == TipoOperacion.Gasto ? transaccion.Monto.ToString("N"): null)</td>
                    </tr>
                }


        }
        </tbody>
    </table>
    
}

ManejoPresupuesto/Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosViewModel


<div class="contenedor-totales mb-3">
    <div>
        <div>
            <strong>Depósitos</strong>
        </div>
        <div class="activo">
            @Model.Ingresos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Retiros</strong>
        </div>
        <div class="pasivo">
            @Model.Gastos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Total</strong>
        </div>
        <div>
            @Model.Total.ToString("N")
        </div>
    </div>
</div>